<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="UnityEngine">
      <HintPath>D:\Steam\steamapps\common\Burglin' Gnomes Demo\Gnomium_Data\Managed\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>D:\Steam\steamapps\common\Burglin' Gnomes Demo\Gnomium_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>D:\Steam\steamapps\common\Burglin' Gnomes Demo\Gnomium_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>D:\Steam\steamapps\common\Burglin' Gnomes Demo\Gnomium_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>D:\Steam\steamapps\common\Burglin' Gnomes Demo\Gnomium_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>D:\Steam\steamapps\common\Burglin' Gnomes Demo\Gnomium_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.Netcode.Runtime">
      <HintPath>D:\Steam\steamapps\common\Burglin' Gnomes Demo\Gnomium_Data\Managed\Unity.Netcode.Runtime.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="com.lightbug.character-controller-pro">
      <HintPath>D:\Steam\steamapps\common\Burglin' Gnomes Demo\Gnomium_Data\Managed\com.lightbug.character-controller-pro.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>